<a href="https://colab.research.google.com/github/springboardmentor443m-coder/Predictive-Public-Transit-Intelligence-Platform-for-Crowd-Management-and-Schedule-Optimization/blob/anumitha-j/PREDICTIVE_CROWD_MONITORING_%26_TRAIN_SCHEDULING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMPORT THE DATASET

In [1]:
import pandas as pd

# Replace with your actual copied path (default is usually '/content/filename')
# Original Google Sheets sharing link:
# 'https://docs.google.com/spreadsheets/d/1v48zcz6rA20FUai0QSrsrED1shVbMBu7/edit?usp=sharing&ouid=102703516643704836876&rtpof=true&sd=true'

# Corrected link for direct Excel download from Google Sheets
file_path = 'https://docs.google.com/spreadsheets/d/1v48zcz6rA20FUai0QSrsrED1shVbMBu7/export?format=xlsx'

# If using an Excel file (.xlsx)
df = pd.read_excel(file_path)

# If using a CSV file (.csv)
# df = pd.read_csv(file_path)

print(f"Dataset successfully loaded: {df.shape[0]} rows, {df.shape[1]} columns")
df.head()

Dataset successfully loaded: 5001 rows, 19 columns

,TripID,Exact_Entry_Timestamp,Exact_Exit_Timestamp,From_Station,To_Station,Train_ID,Line_Color,Transit_Direction,Scheduled_Departure_Time,Actual_Departure_Time,Scheduled_Arrival_Time,Actual_Arrival_Time,Historical Delay (min),Train_Capacity,Train_Occupancy_Count,Occupancy_Rate (%),Platform_Crowd_Density,Headway_Interval_min,Route Congestion
0,1,2023-04-13 18:50:00,2023-04-13 19:13:00,Botanical Garden,Dwarka Sec 21,TR_3887,Magenta Line,Down Line,2023-04-13 18:57:00,2023-04-13 19:07:00,2023-04-13 19:18:00,2023-04-13 19:28:00,10.0,1500,313,20.87,54,2,Low
1,2,2023-12-15 17:23:00,2023-12-15 17:45:00,Kashmere Gate,Kashmere Gate,TR_7516,Blue Line,Down Line,2023-12-15 17:30:00,2023-12-15 17:34:00,2023-12-15 18:36:00,2023-12-15 18:40:00,4.0,1500,915,61.00,158,2,Medium
2,3,2023-09-28 16:06:00,2023-09-28 17:33:00,Botanical Garden,Dwarka Sec 21,TR_8905,Magenta Line,Up Line,2023-09-28 16:13:00,2023-09-28 16:21:00,2023-09-28 16:47:00,2023-09-28 16:55:00,8.0,1500,306,20.40,52,2,Low
3,4,2023-04-17 23:15:00,2023-04-18 00:03:00,Rajiv Chowk,Hauz Khas,TR_2995,Magenta Line,Up Line,2023-04-17 23:22:00,2023-04-17 23:22:00,2023-04-18 00:24:00,2023-04-18 00:24:00,NaN,1500,396,26.40,68,9,Low
4,5,2023-03-13 22:05:00,2023-03-13 22:52:00,Botanical Garden,Rajiv Chowk,TR_4577,Magenta Line,Down Line,2023-03-13 22:12:00,2023-03-13 22:26:00,2023-03-13 22:34:00,2023-03-13 22:48:00,14.0,1500,1287,85.80,222,12,High

# DATA INSPECTION AND DATA CLEANING :

Missing Values: Are there any columns with NaN or 0 counts? If so, we will need to handle them (imputation or dropping).


Datetime Conversion: Ensure the print statements confirm the time columns were converted. If they stay as object (strings), the ML model cannot calculate delays or headways.


Summary Statistics: Look at the min and max for Train_Occupancy_Count and Historical Delay (min) to ensure there are no extreme outliers (e.g., negative passengers or a 5000-minute delay).

In [2]:
# TO CHECK ROWS AND COLUMNS

print("Shape:", df.shape)

Shape: (5001, 19)

In [3]:
# 1. CHECK DATA TYPES AND MISSING VALUES
print("--- Data Schema & Non-Null Counts ---")
df.info()

--- Data Schema & Non-Null Counts ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   TripID                    5001 non-null   int64
 1   Exact_Entry_Timestamp     5001 non-null   object
 2   Exact_Exit_Timestamp      5001 non-null   object
 3   From_Station              5001 non-null   object
 4   To_Station                5001 non-null   object
 5   Train_ID                  5001 non-null   object
 6   Line_Color                5001 non-null   object
 7   Transit_Direction         5001 non-null   object
 8   Scheduled_Departure_Time  5001 non-null   object
 9   Actual_Departure_Time     5001 non-null   object
 10  Scheduled_Arrival_Time    5001 non-null   object
 11  Actual_Arrival_Time       5001 non-null   object
 12  Historical Delay (min)    4994 non-null   float64
 13  Train_Capacity            5001 non-null   int64
 14  Train_Occupancy_Count     5001 non-null   int64
 15  Occupancy_Rate (%)        5001 non-null   float64
 16  Platform_Crowd_Density    5001 non-null   int64
 17  Headway_Interval_min      5001 non-null   int64
 18  Route Congestion          5001 non-null   object
dtypes: float64(2), int64(5), object(12)
memory usage: 742.5+ KB

In [4]:
# TO VIEW COLUMNS :

df.columns

Index(['TripID', 'Exact_Entry_Timestamp', 'Exact_Exit_Timestamp',
       'From_Station', 'To_Station', 'Train_ID', 'Line_Color',
       'Transit_Direction', 'Scheduled_Departure_Time',
       'Actual_Departure_Time', 'Scheduled_Arrival_Time',
       'Actual_Arrival_Time', 'Historical Delay (min)', 'Train_Capacity',
       'Train_Occupancy_Count', 'Occupancy_Rate (%)', 'Platform_Crowd_Density',
       'Headway_Interval_min', 'Route Congestion'],
      dtype='object')

In [5]:
# MISSING VALUE COUNT PER COLUMN
print("\n--- Missing Value Count per Column ---")
print(df.isnull().sum())

--- Missing Value Count per Column ---
TripID                      0
Exact_Entry_Timestamp       0
Exact_Exit_Timestamp        0
From_Station                0
To_Station                  0
Train_ID                    0
Line_Color                  0
Transit_Direction           0
Scheduled_Departure_Time    0
Actual_Departure_Time       0
Scheduled_Arrival_Time      0
Actual_Arrival_Time         0
Historical Delay (min)      7
Train_Capacity              0
Train_Occupancy_Count       0
Occupancy_Rate (%)          0
Platform_Crowd_Density      0
Headway_Interval_min        0
Route Congestion            0
dtype: int64

In [6]:
# ASSUMING MISSING AS O USING ' df.fillna() '

df['Historical Delay (min)'] = df['Historical Delay (min)'].fillna(0)

In [7]:
# VERIFY REMOVAL

print("Remaining missing values:", df['Historical Delay (min)'].isnull().sum())

Remaining missing values: 0

In [8]:
# TO VIEW COLUMNS

df.columns

Index(['TripID', 'Exact_Entry_Timestamp', 'Exact_Exit_Timestamp',
       'From_Station', 'To_Station', 'Train_ID', 'Line_Color',
       'Transit_Direction', 'Scheduled_Departure_Time',
       'Actual_Departure_Time', 'Scheduled_Arrival_Time',
       'Actual_Arrival_Time', 'Historical Delay (min)', 'Train_Capacity',
       'Train_Occupancy_Count', 'Occupancy_Rate (%)', 'Platform_Crowd_Density',
       'Headway_Interval_min', 'Route Congestion'],
      dtype='object')

In [9]:
# 2. Convert Time Columns to Datetime Objects
# This is crucial for time-series forecasting in transit data

timestamp_cols = [
    'Exact_Entry_Timestamp', 'Exact_Exit_Timestamp',
    'Scheduled_Departure_Time', 'Actual_Departure_Time',
    'Scheduled_Arrival_Time', 'Actual_Arrival_Time'
]

In [10]:
df.dtypes

TripID                        int64
Exact_Entry_Timestamp        object
Exact_Exit_Timestamp         object
From_Station                 object
To_Station                   object
Train_ID                     object
Line_Color                   object
Transit_Direction            object
Scheduled_Departure_Time     object
Actual_Departure_Time        object
Scheduled_Arrival_Time       object
Actual_Arrival_Time          object
Historical Delay (min)      float64
Train_Capacity                int64
Train_Occupancy_Count         int64
Occupancy_Rate (%)          float64
Platform_Crowd_Density        int64
Headway_Interval_min          int64
Route Congestion             object
dtype: object

In [11]:
# Apply conversion of object to datetime datatype , only to columns that exist in your dataset
for col in timestamp_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col])
        print(f"Successfully converted {col} to datetime.")

Successfully converted Exact_Entry_Timestamp to datetime.
Successfully converted Exact_Exit_Timestamp to datetime.
Successfully converted Scheduled_Departure_Time to datetime.
Successfully converted Actual_Departure_Time to datetime.
Successfully converted Scheduled_Arrival_Time to datetime.
Successfully converted Actual_Arrival_Time to datetime.

In [12]:
df.dtypes

TripID                               int64
Exact_Entry_Timestamp       datetime64[ns]
Exact_Exit_Timestamp        datetime64[ns]
From_Station                        object
To_Station                          object
Train_ID                            object
Line_Color                          object
Transit_Direction                   object
Scheduled_Departure_Time    datetime64[ns]
Actual_Departure_Time       datetime64[ns]
Scheduled_Arrival_Time      datetime64[ns]
Actual_Arrival_Time         datetime64[ns]
Historical Delay (min)             float64
Train_Capacity                       int64
Train_Occupancy_Count                int64
Occupancy_Rate (%)                 float64
Platform_Crowd_Density               int64
Headway_Interval_min                 int64
Route Congestion                    object
dtype: object

In [13]:
# 3. View Summary Statistics for Numerical Data
print("\n--- Summary Statistics ---")
df.describe()

--- Summary Statistics ---

,TripID,Exact_Entry_Timestamp,Exact_Exit_Timestamp,Scheduled_Departure_Time,Actual_Departure_Time,Scheduled_Arrival_Time,Actual_Arrival_Time,Historical Delay (min),Train_Capacity,Train_Occupancy_Count,Occupancy_Rate (%),Platform_Crowd_Density,Headway_Interval_min
count,5001.000000,5001,5001,5001,5001,5001,5001,5001.000000,5001.000000,5001.000000,5001.000000,5001.000000,5001.000000
mean,2500.999800,2023-07-02 02:10:14.949010176,2023-07-02 03:01:32.201559552,2023-07-02 02:17:14.949010176,2023-07-02 02:24:17.480503808,2023-07-02 02:56:29.706058752,2023-07-02 03:03:32.237552384,7.042192,1898.620276,1203.543091,63.373689,207.868026,4.964407
min,1.000000,2023-01-01 06:52:00,2023-01-01 07:53:00,2023-01-01 06:59:00,2023-01-01 07:10:00,2023-01-01 08:14:00,2023-01-01 08:25:00,0.000000,1500.000000,150.000000,10.000000,25.000000,2.000000
25%,1251.000000,2023-04-03 18:08:00,2023-04-03 18:32:00,2023-04-03 18:15:00,2023-04-03 18:26:00,2023-04-03 18:53:00,2023-04-03 19:01:00,3.000000,1500.000000,793.000000,44.800000,137.000000,3.000000
50%,2501.000000,2023-06-28 16:12:00,2023-06-28 17:07:00,2023-06-28 16:19:00,2023-06-28 16:30:00,2023-06-28 16:48:00,2023-06-28 16:59:00,7.000000,1800.000000,1213.000000,66.280000,210.000000,4.000000
75%,3751.000000,2023-10-01 19:16:00,2023-10-01 20:31:00,2023-10-01 19:23:00,2023-10-01 19:29:00,2023-10-01 19:47:00,2023-10-01 19:53:00,11.000000,2400.000000,1548.000000,85.130000,268.000000,6.000000
max,5000.000000,2023-12-31 21:06:00,2023-12-31 21:51:00,2023-12-31 21:13:00,2023-12-31 21:23:00,2023-12-31 21:52:00,2023-12-31 21:59:00,14.000000,2400.000000,2399.000000,99.960000,415.000000,14.000000
std,1443.808332,NaN,NaN,NaN,NaN,NaN,NaN,4.278226,373.245356,536.873339,24.860082,92.951552,3.453973

In [14]:
# TO CHECK THE DUPLICATES

print("Duplicates:", df.duplicated().sum())

Duplicates: 1

In [15]:
# DROP DUPLICATES

df = df.drop_duplicates()

In [16]:
# Verify duplicates are 0

print("Duplicates remaining:", df.duplicated().sum())

Duplicates remaining: 0

# FEATURE ENGINEERING:

Feature engineering is the process of translating raw data into a mathematical language that machine learning algorithms can actually understand. While a human looks at "2023-04-13 18:50:00" and instantly recognizes it as the evening rush hour, an algorithm just sees a meaningless string of text. You have to break that raw data down into explicit, numerical signals.

# Temporal Extraction:

Machine learning models need time broken into distinct categories. You extract the hour, the day of the week, and create binary flags (1 or 0) for business logic, such as whether a specific trip falls inside the morning or evening peak rush.

In [17]:
import numpy as np

# 1. Temporal Extraction
df['Entry_Hour'] = df['Exact_Entry_Timestamp'].dt.hour
df['Day_of_Week'] = df['Exact_Entry_Timestamp'].dt.day_name()
df['Is_Weekend'] = df['Exact_Entry_Timestamp'].dt.weekday.isin([5, 6]).astype(int)

In [18]:
# 2. Create the Peak Hour Flag that marks rush hour times with a 1 and all other times with a 0.

df['Is_Peak_Hour'] = df['Entry_Hour'].apply(
    lambda h: 1 if (8 <= h <= 11) or (17 <= h <= 20) else 0
)

It flags two peak windows based on the Entry_Hour column:Morning peak: 8:00 AM – 11:59 AM (hours 8–11)Evening peak: 5:00 PM – 8:59 PM (hours 17–20)

# Cyclical Encoding :

Algorithms do not inherently know that Hour 23 (11 PM) and Hour 0 (Midnight) are right next to each other. If you just feed them the numbers 0 to 23, they think midnight and 11 PM are as far apart as possible. You apply " Sine and Cosine transformations " to the hour to teach the model the continuous, circular loop of a 24-hour clock.

In [19]:
# 3. Cyclical Encoding (Teaching the model the 24-hour loop)

df['Hour_Sin'] = np.sin(2 * np.pi * df['Entry_Hour'] / 24.0)
df['Hour_Cos'] = np.cos(2 * np.pi * df['Entry_Hour'] / 24.0)

# Domain Metric Calculation

You combine existing columns to engineer the actual targets your model needs to predict. For example, subtracting the Scheduled_Departure_Time from the Actual_Departure_Time gives you the exact Computed_Delay_min.

In [20]:
# 4. Domain Metric Calculation
# Calculate real delay in minutes

df['Computed_Delay_min'] = (
    df['Actual_Departure_Time'] - df['Scheduled_Departure_Time']
).dt.total_seconds() / 60.0

# LABEL ENCODING

Label Encoding means converting text into numbers so a computer can understand it. Each unique text category gets its own number.


# EXAMPLE :

Computers only look at math: Machine learning models cannot read words like "Small" or "Large."Keeps the order: It works perfectly for shirts because the numbers match the size order (0 < 1 < 2).

Algorithms cannot multiply or split text like "Yellow Line" or "Rajiv Chowk." Later, right before model training, these strings are converted into binary arrays (One-Hot Encoding) or numerical IDs (Label Encoding).

# You are applying transit logic to combine two raw timestamps into a new, highly relevant numerical feature.

In [21]:
# Calculate platform dwell time (how long the train sits at the station)
df['Dwell_Time_min'] = (
    df['Actual_Departure_Time'] - df['Actual_Arrival_Time']
).dt.total_seconds() / 60.0

In [22]:
# 5. Verify all newly engineered features
engineered_cols = [
    'Entry_Hour', 'Day_of_Week', 'Is_Peak_Hour',
    'Hour_Sin', 'Hour_Cos', 'Computed_Delay_min', 'Dwell_Time_min'
]

In [23]:
df[engineered_cols].head()

,Entry_Hour,Day_of_Week,Is_Peak_Hour,Hour_Sin,Hour_Cos,Computed_Delay_min,Dwell_Time_min
0,18,Thursday,1,-1.000000,-1.836970e-16,10.0,-21.0
1,17,Friday,1,-0.965926,-2.588190e-01,4.0,-66.0
2,16,Thursday,0,-0.866025,-5.000000e-01,8.0,-34.0
3,23,Monday,0,-0.258819,9.659258e-01,0.0,-62.0
4,22,Monday,0,-0.500000,8.660254e-01,14.0,-22.0